const AUTH_REQUESTED = 'AUTH_REQUESTED';
const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
const AUTH_UNSUCCESSFUL = 'AUTH_UNSUCCESSFUL';

export default {
    AUTH_REQUESTED,
    AUTH_SUCCESSFUL,
    AUTH_UNSUCCESSFUL
}
